trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: AzureCLI@2
  displayName: 'Terraform Init'
  inputs:
    azureSubscription: 'azure-terraform-sc'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      terraform init

- task: AzureCLI@2
  displayName: 'Terraform Format Check'
  inputs:
    azureSubscription: 'azure-terraform-sc'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      terraform fmt -check

- task: AzureCLI@2
  displayName: 'Terraform Validate'
  inputs:
    azureSubscription: 'azure-terraform-sc'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      terraform validate

- task: AzureCLI@2
  displayName: 'Terraform Plan'
  inputs:
    azureSubscription: 'azure-terraform-sc'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      terraform plan

# Uncomment later after testing

# - task: AzureCLI@2
#   displayName: 'Terraform Apply'
#   inputs:
#     azureSubscription: 'azure-terraform-sc'
#     scriptType: bash
#     scriptLocation: inlineScript
#     inlineScript: |
#       terraform apply -auto-approve